spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5433/user_management_db
    username: postgres
    password: PasswordSQL123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true